import type { Metadata } from "next";

import { Archivo } from "next/font/google";

import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { ReactQueryProvider } from "@/providers/QueryClient";

const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className="no-scrollbar">
      <body className={inter.className}>
        <main>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
